'use-strict';

/**
 * The Competence class
 */
class CompetenceDTO {

    /**
     * The constructor of PersonDTO
     * 
     * @param {Integer} personId The id of the newly created competence. 
     *                           This will be automatically generated by the database.
     * @param {String} name The name of the competence
     */
    constructor(id, name) {
        this.id = id;
        this.name = name;

    }
}
module.exports = CompetenceDTO;